import React, { useState } from 'react';
import '../styles/ToxinMetabolites.css';

// Dummy JSON data
const dummyData = {
  environmentalToxins: {
    pesticides: [
      {
        id: 1,
        name: "ORGANOCHLORINES",
        overview: "Organochlorine pesticides are still used in some developing countries for both agricultural and public health purposes.",
        functionsImpacted: ["Weight management", "Sugar metabolism", "Immunity", "Mental wellness"],
        percentile: 30,
        percentileText: "Your exposure to this toxin is less than 30% of the studied population. You are in the 30th percentile"
      },
      {
        id: 2,
        name: "NEONICOTINOIDS",
        overview: "Neonicotinoids are among the widest-used insecticides in crop protection. They are also widely employed for veterinary purposes including tick and flea control.",
        functionsImpacted: ["Mental wellness", "Immunity"],
        percentile: 70,
        percentileText: "Your exposure to this toxin is less than 70% of the studied population. You are in the 70th percentile"
      },
      {
        id: 3,
        name: "PYRETHROIDS",
        overview: "Pyrethroids are synthetic insecticides used to control pests on a wide variety of crops like cabbage, broccoli etc.",
        functionsImpacted: ["Mental wellness", "Immunity"],
        percentile: 90,
        percentileText: "Your exposure to this toxin is less than 90% of the studied population. You are in the 90th percentile"
      },
      {
        id: 4,
        name: "CARBAMATES",
        overview: "Carbamates are a class of household insecticides. Long-term exposure can result in loss of appetite, weakness, weight loss and a general feeling of sickness.",
        functionsImpacted: [],
        percentile: 10,
        percentileText: "Your exposure to this toxin is less than 10% of the studied population. You are in the 10th percentile"
      }
    ],
    
  },
  beneficialMetabolites: {
    scfas: [
      {
        id: 9,
        name: "ACETATE",
        overview: "Acetate is a short-chain fatty acid (SCFA) produced by gut bacteria during fermentation of dietary fibers and is the most abundant SCFA in the human colon.",
        functionsImpacted: [],
        percentile: 30,
        percentileText: "Your levels of this metabolite is less than 30% of the studied population. You are in the 30th percentile"
      },
      {
        id: 10,
        name: "PROPIONATE",
        overview: "Propionate is an SCFA generated by gut microbes from fiber fermentation and plays a key role in liver metabolism and glucose regulation.",
        functionsImpacted: [],
        percentile: 70,
        percentileText: "Your levels of this metabolite is less than 70% of the studied population. You are in the 70th percentile"
      },
      {
        id: 11,
        name: "BUTYRATE",
        overview: "Butyrate is an SCFA produced by beneficial gut bacteria and serves as the primary energy source for colon cells, supporting gut and immune health.",
        functionsImpacted: [],
        percentile: 90,
        percentileText: "Your levels of this metabolite is less than 90% of the studied population. You are in the 90th percentile"
      }
    ],
  }
};

const ToxinsMetabolites = () => {
  const data = dummyData; // Replace with API data
  
  // State for Environmental Toxins tabs
  const [activeToxinTab, setActiveToxinTab] = useState('pesticides');
  
  // State for Beneficial Metabolites tabs
  const [activeMetaboliteTab, setActiveMetaboliteTab] = useState('scfas');

  // Get current data based on active tabs
  const currentToxinData = data.environmentalToxins[activeToxinTab] || [];
  const currentMetaboliteData = data.beneficialMetabolites[activeMetaboliteTab] || [];

  // Render percentile bar
  const renderPercentileBar = (percentile) => {
    return (
      <div className="percentile-bar-container">
        <div className="percentile-bar">
          <div className="percentile-scale">
            <span className="scale-label">0th</span>
            <span className="scale-label">100th</span>
          </div>
          <div className="percentile-track">
            <div 
              className="percentile-marker" 
              style={{ left: `${percentile}%` }}
            >
              <div className="marker-dot"></div>
              <div className="marker-label">You</div>
            </div>
          </div>
          <div className="percentile-caption">Percentile scale in studied population</div>
        </div>
      </div>
    );
  };

  return (
    <div className="toxins-metabolites-container">
      {/* Environmental Toxins Section */}
      <section className="section-block">
        <h2 className="section-main-title">Environmental Toxins</h2>
        
        <div className="tabs-container">
          <button
            className={`tab-button ${activeToxinTab === 'pesticides' ? 'active' : ''}`}
            onClick={() => setActiveToxinTab('pesticides')}
          >
            Pesticides
          </button>
          <button
            className={`tab-button ${activeToxinTab === 'antibiotics' ? 'active' : ''}`}
            onClick={() => setActiveToxinTab('antibiotics')}
          >
            Antibiotics*
          </button>
          <button
            className={`tab-button ${activeToxinTab === 'steroids' ? 'active' : ''}`}
            onClick={() => setActiveToxinTab('steroids')}
          >
            Steroids*
          </button>
        </div>

        <div className="cards-grid">
          {currentToxinData.length === 0 ? (
            <div className="no-data-message">
              <p>No data available for this category</p>
            </div>
          ) : (
            currentToxinData.map((item) => (
              <div key={item.id} className="info-card">
                <h3 className="card-title">{item.name}</h3>
                <p className="card-overview">{item.overview}</p>
                
                {item.functionsImpacted.length > 0 && (
                  <p className="card-functions">
                    Functions impacted: {item.functionsImpacted.join(', ')}
                  </p>
                )}
                
                <p className="card-percentile-text">{item.percentileText}</p>
                
                {renderPercentileBar(item.percentile)}
              </div>
            ))
          )}
        </div>
      </section>

      {/* Beneficial Metabolites Section */}
      <section className="section-block">
        <h2 className="section-main-title">Beneficial Metabolites*</h2>
        
        <div className="tabs-container">
          <button
            className={`tab-button ${activeMetaboliteTab === 'scfas' ? 'active' : ''}`}
            onClick={() => setActiveMetaboliteTab('scfas')}
          >
            SCFAs
          </button>
          <button
            className={`tab-button ${activeMetaboliteTab === 'vitamins' ? 'active' : ''}`}
            onClick={() => setActiveMetaboliteTab('vitamins')}
          >
            Vitamins
          </button>
          <button
            className={`tab-button ${activeMetaboliteTab === 'aminoAcids' ? 'active' : ''}`}
            onClick={() => setActiveMetaboliteTab('aminoAcids')}
          >
            Amino acids
          </button>
        </div>

        <div className="cards-grid">
          {currentMetaboliteData.length === 0 ? (
            <div className="no-data-message">
              <p>No data available for this category</p>
            </div>
          ) : (
            currentMetaboliteData.map((item) => (
              <div key={item.id} className="info-card">
                <h3 className="card-title">{item.name}</h3>
                <p className="card-overview">{item.overview}</p>
                
                {item.functionsImpacted.length > 0 && (
                  <p className="card-functions">
                    Functions impacted: {item.functionsImpacted.join(', ')}
                  </p>
                )}
                
                <p className="card-percentile-text">{item.percentileText}</p>
                
                {renderPercentileBar(item.percentile)}
              </div>
            ))
          )}
        </div>
      </section>
    </div>
  );
};

export default ToxinsMetabolites;